<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Returns   Orders</name>
   <tag></tag>
   <elementGuidId>7508cd78-ffe5-43f1-b905-72a4f2659f61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-orders']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-orders</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>657ec48d-8635-4b2b-b449-f45b194b39b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/gp/css/order-history?ref_=nav_orders_first</value>
      <webElementGuid>ca6e03a2-9ec8-4924-9210-7721405a02df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-a nav-a-2   nav-progressive-attribute</value>
      <webElementGuid>fdb08bea-a6c2-47e6-a3c3-9b1b3ba55f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-orders</value>
      <webElementGuid>8bf12ffb-513f-4090-9c37-db9b43fe06fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8c5dff7b-f1bf-475b-afac-e8094a3b0e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  Returns
  &amp; Orders
</value>
      <webElementGuid>3d47ed10-3370-4621-be96-db794b7b22f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-orders&quot;)</value>
      <webElementGuid>106b1383-a8c1-43c8-ac9f-a075909ad3fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-orders']</value>
      <webElementGuid>98021b03-bc2e-45e6-af55-740ced22a475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-tools']/a[3]</value>
      <webElementGuid>7af9fe2d-43dd-4bfc-bb62-582033de8a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/gp/css/order-history?ref_=nav_orders_first')]</value>
      <webElementGuid>0b31871c-6294-410b-b3e2-2ebaa0c5c53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a[3]</value>
      <webElementGuid>c1edc294-daa8-466c-be3e-abbc5b805c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/gp/css/order-history?ref_=nav_orders_first' and @id = 'nav-orders' and (text() = '
  Returns
  &amp; Orders
' or . = '
  Returns
  &amp; Orders
')]</value>
      <webElementGuid>a4a8da59-94b6-425a-a4e6-54e95728e563</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
